require("arthur.plugins-setup")
require("arthur.core.options")
require("arthur.core.keymaps")
require("arthur.core.colorscheme")

require("arthur.plugins.comment")
require("arthur.plugins.copilot")
require("arthur.plugins.gitsigns")
require("arthur.plugins.treesitter")
require("arthur.plugins.telescope")
require("arthur.plugins.lualine")
require("arthur.plugins.nvim-tree")
require("arthur.plugins.nvim-cmp")
require("arthur.plugins.lsp.mason")
require("arthur.plugins.lsp.lspsaga")
require("arthur.plugins.lsp.lspconfig")
require("arthur.autostart")
